import './globals.css';
import type { Metadata } from 'next';
import { Geist_Mono, Inter } from 'next/font/google';
import { Header } from '@/components/index';
import { InvitesProvider } from './providers/InvitesProvider';
import { LessonsProvider } from './providers/LessonsProvider';

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin', 'cyrillic'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
                <InvitesProvider>
                    <LessonsProvider>
                        <Header />
                        <main className="container mx-auto">{children}</main>
                    </LessonsProvider>
                </InvitesProvider>
            </body>
        </html>
    );
}
